"""Built-in marketplace + template catalog for skills, workflows, and departments."""

from __future__ import annotations

from typing import Any

MARKETPLACE_SKILLS: list[dict[str, Any]] = [
    {
        "slug": "web-research-specialist",
        "name": "Web Research Specialist",
        "category": "research",
        "department": "R&D",
        "description": "Plan and execute structured web research with source verification.",
        "capabilities": ["web_research", "source_verification", "structured_extraction"],
        "required_tools": ["web_search", "web_fetch"],
        "risk_level": "low",
        "purpose": "Produce cited research briefs from public sources.",
        "when_to_use": "When a task needs multi-source public web research.",
        "instructions_markdown": (
            "Clarify the research question, search authoritative sources, fetch key pages, "
            "extract facts with citations, and return a structured brief."
        ),
    },
    {
        "slug": "greenhouse-lead-qualifier",
        "name": "Greenhouse Lead Qualifier",
        "category": "sales",
        "department": "Sales",
        "description": "Qualify greenhouse / agri operators against an ICP.",
        "capabilities": [
            "company_discovery",
            "company_enrichment",
            "greenhouse_classification",
            "lead_qualification",
        ],
        "required_tools": ["web_search", "web_fetch"],
        "risk_level": "medium",
        "purpose": "Build a qualified prospect dataset for agricultural sales.",
        "when_to_use": "Sales expansion tasks targeting greenhouse operators.",
        "instructions_markdown": (
            "Discover companies, classify greenhouse operations, enrich firmographics, "
            "verify sources, and score against ICP. Output a tabular prospect dataset."
        ),
    },
    {
        "slug": "github-issue-fixer",
        "name": "GitHub Issue Fixer",
        "category": "engineering",
        "department": "Engineering",
        "description": "Investigate issues, patch code, test, and open PRs.",
        "capabilities": [
            "code_investigation",
            "code_modification",
            "test_execution",
            "pr_creation",
        ],
        "required_tools": [
            "repo_search",
            "fs_read",
            "fs_write",
            "code_execute",
            "github_create_pr",
        ],
        "risk_level": "high",
        "purpose": "Resolve engineering defects with reviewed pull requests.",
        "when_to_use": "When a GitHub issue needs investigation and a fix.",
        "instructions_markdown": (
            "Reproduce the defect, implement a minimal fix, run relevant tests, "
            "summarize evidence, and open a pull request."
        ),
    },
    {
        "slug": "campaign-brief-writer",
        "name": "Campaign Brief Writer",
        "category": "marketing",
        "department": "Marketing",
        "description": "Draft campaign briefs and channel plans.",
        "capabilities": ["campaign_planning", "content_drafting"],
        "required_tools": ["web_search", "knowledge_search"],
        "risk_level": "low",
        "purpose": "Produce reviewable marketing campaign briefs.",
        "when_to_use": "When marketing needs a structured campaign plan.",
        "instructions_markdown": (
            "Capture audience, offer, channels, KPIs, and creative direction. "
            "Return a brief ready for human review."
        ),
    },
    {
        "slug": "ops-runbook-executor",
        "name": "Ops Runbook Executor",
        "category": "operations",
        "department": "Operations",
        "description": "Follow operational runbooks with checkpoints.",
        "capabilities": ["runbook_execution", "status_reporting"],
        "required_tools": ["knowledge_search", "web_fetch"],
        "risk_level": "medium",
        "purpose": "Execute ops procedures with evidence at each step.",
        "when_to_use": "When operational playbooks must be followed carefully.",
        "instructions_markdown": (
            "Load the runbook, execute steps in order, pause for approvals when required, "
            "and record evidence for each checkpoint."
        ),
    },
    {
        "slug": "literature-reviewer",
        "name": "Literature Reviewer",
        "category": "research",
        "department": "R&D",
        "description": "Synthesize literature and produce research reports.",
        "capabilities": ["literature_review", "experiment_planning"],
        "required_tools": ["web_search", "web_fetch", "knowledge_search"],
        "risk_level": "low",
        "purpose": "Create literature reviews and experiment plans.",
        "when_to_use": "R&D exploration tasks.",
        "instructions_markdown": (
            "Collect papers/articles, summarize methods and findings, identify gaps, "
            "and propose next experiments."
        ),
    },
]

MARKETPLACE_WORKFLOWS: list[dict[str, Any]] = [
    {
        "slug": "research-then-review",
        "name": "Research → Review",
        "category": "research",
        "description": "Agent research followed by human approval.",
        "nodes": [
            {"id": "research", "type": "agent", "label": "Research"},
            {"id": "approve", "type": "approval", "label": "Human review"},
        ],
        "edges": [{"from": "research", "to": "approve"}],
        "entry_node_id": "research",
    },
    {
        "slug": "sales-prospecting",
        "name": "Sales Prospecting",
        "category": "sales",
        "description": "Skill coverage then agent execution then approval.",
        "nodes": [
            {"id": "skills", "type": "skill", "label": "Ensure skills"},
            {"id": "execute", "type": "agent", "label": "Prospect"},
            {"id": "approve", "type": "approval", "label": "Sales review"},
        ],
        "edges": [
            {"from": "skills", "to": "execute"},
            {"from": "execute", "to": "approve"},
        ],
        "entry_node_id": "skills",
    },
    {
        "slug": "engineering-fix-pr",
        "name": "Engineering Fix + PR",
        "category": "engineering",
        "description": "Investigate, patch, test, open PR, review.",
        "nodes": [
            {"id": "investigate", "type": "agent", "label": "Investigate"},
            {"id": "patch", "type": "tool", "label": "Apply patch tools"},
            {"id": "review", "type": "approval", "label": "PR review"},
        ],
        "edges": [
            {"from": "investigate", "to": "patch"},
            {"from": "patch", "to": "review"},
        ],
        "entry_node_id": "investigate",
    },
    {
        "slug": "marketing-campaign",
        "name": "Marketing Campaign Draft",
        "category": "marketing",
        "description": "Draft campaign then human approval.",
        "nodes": [
            {"id": "draft", "type": "agent", "label": "Draft brief"},
            {"id": "approve", "type": "approval", "label": "Marketing approval"},
        ],
        "edges": [{"from": "draft", "to": "approve"}],
        "entry_node_id": "draft",
    },
    {
        "slug": "ops-incident",
        "name": "Ops Incident Runbook",
        "category": "operations",
        "description": "Trigger → runbook agent → approval.",
        "nodes": [
            {"id": "trigger", "type": "trigger", "label": "Incident trigger"},
            {"id": "runbook", "type": "agent", "label": "Execute runbook"},
            {"id": "approve", "type": "approval", "label": "Ops sign-off"},
        ],
        "edges": [
            {"from": "trigger", "to": "runbook"},
            {"from": "runbook", "to": "approve"},
        ],
        "entry_node_id": "trigger",
    },
]

MARKETPLACE_DEPARTMENTS: list[dict[str, Any]] = [
    {
        "slug": "engineering",
        "name": "Engineering",
        "description": "Software delivery, code review, and GitHub integrations.",
        "default_tool_policy": {
            "preferred_tools": ["repo_search", "fs_read", "code_execute", "github_create_pr"]
        },
        "default_model_policy": {"temperature": 0.2},
        "default_approval_policy": {"high_risk_tools": "approval_required"},
    },
    {
        "slug": "sales",
        "name": "Sales",
        "description": "Prospecting, qualification, and CRM-oriented research.",
        "default_tool_policy": {"preferred_tools": ["web_search", "web_fetch"]},
        "default_model_policy": {"temperature": 0.4},
        "default_approval_policy": {"outbound_comms": "approval_required"},
    },
    {
        "slug": "marketing",
        "name": "Marketing",
        "description": "Campaigns, content, and SEO research.",
        "default_tool_policy": {"preferred_tools": ["web_search", "knowledge_search"]},
        "default_model_policy": {"temperature": 0.6},
        "default_approval_policy": {"publish": "approval_required"},
    },
    {
        "slug": "research-rd",
        "name": "R&D",
        "description": "Literature review, experiments, and exploratory research.",
        "default_tool_policy": {"preferred_tools": ["web_search", "web_fetch", "knowledge_search"]},
        "default_model_policy": {"temperature": 0.3},
        "default_approval_policy": {},
    },
    {
        "slug": "operations",
        "name": "Operations",
        "description": "Runbooks, incidents, and operational checklists.",
        "default_tool_policy": {"preferred_tools": ["knowledge_search", "web_fetch"]},
        "default_model_policy": {"temperature": 0.2},
        "default_approval_policy": {"destructive": "prohibited"},
    },
    {
        "slug": "customer-success",
        "name": "Customer Success",
        "description": "Account health, onboarding, and support orchestration.",
        "default_tool_policy": {"preferred_tools": ["knowledge_search", "web_fetch"]},
        "default_model_policy": {"temperature": 0.4},
        "default_approval_policy": {"customer_email": "approval_required"},
    },
]

CONNECTOR_CATALOG: list[dict[str, Any]] = [
    {
        "slug": "mcp-http",
        "name": "MCP HTTP Server",
        "description": "Connect to an MCP server over JSON-RPC HTTP.",
        "provider_type": "mcp",
        "config_schema_json": {
            "type": "object",
            "properties": {
                "base_url": {"type": "string"},
                "auth_token": {"type": "string"},
            },
            "required": ["base_url"],
        },
    },
    {
        "slug": "a2a-http",
        "name": "A2A External Agent",
        "description": "Connect to an external Agent-to-Agent endpoint.",
        "provider_type": "a2a",
        "config_schema_json": {
            "type": "object",
            "properties": {
                "base_url": {"type": "string"},
                "card_url": {"type": "string"},
                "auth_token": {"type": "string"},
            },
            "required": ["base_url"],
        },
    },
]


def _skill(
    slug: str,
    name: str,
    category: str,
    department: str,
    description: str,
    capabilities: list[str],
    tools: list[str],
    risk: str,
    purpose: str,
    when: str,
    instructions: str,
) -> dict[str, Any]:
    return {
        "slug": slug,
        "name": name,
        "category": category,
        "department": department,
        "description": description,
        "capabilities": capabilities,
        "required_tools": tools,
        "risk_level": risk,
        "purpose": purpose,
        "when_to_use": when,
        "instructions_markdown": instructions,
    }


# Expand marketplace with a larger cross-department catalog.
MARKETPLACE_SKILLS.extend(
    [
        _skill(
            "seo-content-auditor",
            "SEO Content Auditor",
            "marketing",
            "Marketing",
            "Audit pages for SEO gaps and recommend fixes.",
            ["seo_audit", "content_analysis"],
            ["web_fetch", "web_search"],
            "low",
            "Produce actionable SEO audits.",
            "When marketing needs page-level SEO review.",
            "Fetch target pages, compare against SEO heuristics, and return prioritized fixes.",
        ),
        _skill(
            "competitor-teardown",
            "Competitor Teardown",
            "sales",
            "Sales",
            "Compare competitors on positioning, pricing, and features.",
            ["competitive_analysis", "web_research"],
            ["web_search", "web_fetch"],
            "low",
            "Produce competitor comparison briefs.",
            "When sales needs competitive battlecards.",
            "Research competitors, extract claims/pricing, and summarize differentiation.",
        ),
        _skill(
            "incident-triage",
            "Incident Triage",
            "operations",
            "Operations",
            "Triage incidents with severity, owners, and next actions.",
            ["incident_triage", "status_reporting"],
            ["knowledge_search", "web_fetch"],
            "high",
            "Stabilize incidents with structured triage.",
            "When an ops incident needs rapid classification.",
            "Collect symptoms, classify severity, propose owners and next steps.",
        ),
        _skill(
            "code-reviewer",
            "Code Reviewer",
            "engineering",
            "Engineering",
            "Review diffs for correctness, risk, and test gaps.",
            ["code_review", "risk_assessment"],
            ["repo_search", "fs_read"],
            "medium",
            "Produce structured code review feedback.",
            "When a PR needs review notes before merge.",
            "Inspect changed files, note risks, and request tests where missing.",
        ),
        _skill(
            "onboarding-playbook",
            "Customer Onboarding Playbook",
            "customer_success",
            "Customer Success",
            "Guide new accounts through onboarding milestones.",
            ["onboarding", "account_health"],
            ["knowledge_search"],
            "low",
            "Drive structured customer onboarding.",
            "When a new customer starts implementation.",
            "Follow milestones, track blockers, and escalate when stalled.",
        ),
        _skill(
            "data-cleanup",
            "Dataset Cleanup",
            "operations",
            "Operations",
            "Normalize messy tabular datasets for analysis.",
            ["data_cleaning", "structured_extraction"],
            ["fs_read", "fs_write", "code_execute"],
            "medium",
            "Produce cleaned datasets with change notes.",
            "When raw exports need normalization.",
            "Profile columns, fix types/duplicates, and document transformations.",
        ),
        _skill(
            "pr-release-notes",
            "PR Release Notes Writer",
            "engineering",
            "Engineering",
            "Turn merged PRs into customer-facing release notes.",
            ["release_notes", "summarization"],
            ["repo_search", "fs_read"],
            "low",
            "Draft clear release notes from changes.",
            "When preparing a release announcement.",
            "Summarize user-visible changes and call out breaking updates.",
        ),
        _skill(
            "hypothesis-designer",
            "Experiment Hypothesis Designer",
            "research",
            "R&D",
            "Design testable hypotheses and measurement plans.",
            ["experiment_planning", "metrics_design"],
            ["knowledge_search", "web_search"],
            "low",
            "Create experiment designs ready for review.",
            "When R&D needs a measurable experiment plan.",
            "State hypothesis, method, metrics, and stop criteria.",
        ),
        _skill(
            "support-reply-drafter",
            "Support Reply Drafter",
            "customer_success",
            "Customer Success",
            "Draft empathetic support replies with next steps.",
            ["support_drafting", "knowledge_retrieval"],
            ["knowledge_search"],
            "medium",
            "Draft support responses for human approval.",
            "When CS needs a reply draft from knowledge base.",
            "Retrieve relevant docs, draft a reply, and flag uncertainty.",
        ),
        _skill(
            "pipeline-forecaster",
            "Pipeline Forecaster",
            "sales",
            "Sales",
            "Summarize pipeline health and forecast risks.",
            ["pipeline_analysis", "forecasting"],
            ["knowledge_search", "web_search"],
            "low",
            "Produce pipeline forecast summaries.",
            "When sales leadership needs weekly forecast notes.",
            "Aggregate deal stages, highlight risks, and propose actions.",
        ),
        _skill(
            "brand-voice-editor",
            "Brand Voice Editor",
            "marketing",
            "Marketing",
            "Rewrite copy to match brand voice guidelines.",
            ["content_editing", "brand_voice"],
            ["knowledge_search"],
            "low",
            "Align drafts to brand voice.",
            "When marketing copy needs voice consistency.",
            "Apply brand rules and return revised copy with change notes.",
        ),
        _skill(
            "security-checklist",
            "Security Checklist Runner",
            "engineering",
            "Engineering",
            "Run a lightweight security checklist against a change set.",
            ["security_review", "checklist_execution"],
            ["repo_search", "fs_read"],
            "high",
            "Surface security checklist findings.",
            "When changes touch auth, secrets, or data access.",
            "Apply checklist items, record evidence, and escalate blockers.",
        ),
    ]
)

MARKETPLACE_WORKFLOWS.extend(
    [
        {
            "slug": "cs-onboarding",
            "name": "Customer Onboarding",
            "category": "customer_success",
            "description": "Onboarding agent then CS approval.",
            "nodes": [
                {"id": "onboard", "type": "agent", "label": "Onboard"},
                {"id": "approve", "type": "approval", "label": "CS review"},
            ],
            "edges": [{"from": "onboard", "to": "approve"}],
            "entry_node_id": "onboard",
        },
        {
            "slug": "seo-audit-flow",
            "name": "SEO Audit Flow",
            "category": "marketing",
            "description": "Audit then marketing approval.",
            "nodes": [
                {"id": "audit", "type": "agent", "label": "SEO audit"},
                {"id": "approve", "type": "approval", "label": "Marketing review"},
            ],
            "edges": [{"from": "audit", "to": "approve"}],
            "entry_node_id": "audit",
        },
        {
            "slug": "competitor-intel",
            "name": "Competitor Intelligence",
            "category": "sales",
            "description": "Research competitors then sales review.",
            "nodes": [
                {"id": "research", "type": "agent", "label": "Research"},
                {"id": "approve", "type": "approval", "label": "Sales review"},
            ],
            "edges": [{"from": "research", "to": "approve"}],
            "entry_node_id": "research",
        },
        {
            "slug": "code-review-gate",
            "name": "Code Review Gate",
            "category": "engineering",
            "description": "Review agent then approval gate.",
            "nodes": [
                {"id": "review", "type": "agent", "label": "Review"},
                {"id": "approve", "type": "approval", "label": "Merge approval"},
            ],
            "edges": [{"from": "review", "to": "approve"}],
            "entry_node_id": "review",
        },
        {
            "slug": "incident-response",
            "name": "Incident Response",
            "category": "operations",
            "description": "Triage → runbook → ops approval.",
            "nodes": [
                {"id": "triage", "type": "agent", "label": "Triage"},
                {"id": "runbook", "type": "skill", "label": "Runbook"},
                {"id": "approve", "type": "approval", "label": "Ops sign-off"},
            ],
            "edges": [
                {"from": "triage", "to": "runbook"},
                {"from": "runbook", "to": "approve"},
            ],
            "entry_node_id": "triage",
        },
    ]
)

AGENT_TEMPLATE_CATALOG: list[dict[str, Any]] = [
    {
        "slug": "sales-researcher",
        "name": "Sales Researcher",
        "role": "worker",
        "department": "Sales",
        "description": "Researches and qualifies B2B prospects.",
        "capabilities": ["web_research", "lead_qualification", "company_enrichment"],
        "allowed_tools": ["web_search", "web_fetch"],
        "skills": ["greenhouse-lead-qualifier", "web-research-specialist"],
        "tags": ["sales", "research"],
    },
    {
        "slug": "engineering-fixer",
        "name": "Engineering Fixer",
        "role": "worker",
        "department": "Engineering",
        "description": "Fixes defects and opens pull requests.",
        "capabilities": ["code_investigation", "code_modification", "test_execution"],
        "allowed_tools": ["repo_search", "fs_read", "fs_write", "code_execute", "github_create_pr"],
        "skills": ["github-issue-fixer"],
        "tags": ["engineering"],
    },
    {
        "slug": "marketing-strategist",
        "name": "Marketing Strategist",
        "role": "worker",
        "department": "Marketing",
        "description": "Creates campaign briefs and content outlines.",
        "capabilities": ["campaign_planning", "content_drafting"],
        "allowed_tools": ["web_search", "knowledge_search"],
        "skills": ["campaign-brief-writer"],
        "tags": ["marketing"],
    },
    {
        "slug": "ops-coordinator",
        "name": "Ops Coordinator",
        "role": "worker",
        "department": "Operations",
        "description": "Executes operational runbooks with checkpoints.",
        "capabilities": ["runbook_execution", "status_reporting"],
        "allowed_tools": ["knowledge_search", "web_fetch"],
        "skills": ["ops-runbook-executor"],
        "tags": ["operations"],
    },
    {
        "slug": "rd-analyst",
        "name": "R&D Analyst",
        "role": "worker",
        "department": "R&D",
        "description": "Produces literature reviews and experiment plans.",
        "capabilities": ["literature_review", "experiment_planning", "web_research"],
        "allowed_tools": ["web_search", "web_fetch", "knowledge_search"],
        "skills": ["literature-reviewer", "web-research-specialist"],
        "tags": ["research"],
    },
    {
        "slug": "project-manager",
        "name": "Workforce Manager",
        "role": "manager",
        "department": "Operations",
        "description": "Plans work, assigns agents, and reviews outcomes.",
        "capabilities": ["planning", "assignment", "review"],
        "allowed_tools": ["knowledge_search"],
        "skills": [],
        "tags": ["management"],
    },
    {
        "slug": "seo-specialist",
        "name": "SEO Specialist",
        "role": "worker",
        "department": "Marketing",
        "description": "Audits content for SEO gaps.",
        "capabilities": ["seo_audit", "content_analysis"],
        "allowed_tools": ["web_search", "web_fetch"],
        "skills": ["seo-content-auditor"],
        "tags": ["marketing", "seo"],
    },
    {
        "slug": "incident-commander",
        "name": "Incident Commander",
        "role": "worker",
        "department": "Operations",
        "description": "Triages incidents and drives runbooks.",
        "capabilities": ["incident_triage", "runbook_execution"],
        "allowed_tools": ["knowledge_search", "web_fetch"],
        "skills": ["incident-triage", "ops-runbook-executor"],
        "tags": ["operations", "incident"],
    },
    {
        "slug": "code-reviewer-agent",
        "name": "Code Reviewer Agent",
        "role": "worker",
        "department": "Engineering",
        "description": "Reviews diffs and flags risks.",
        "capabilities": ["code_review", "risk_assessment"],
        "allowed_tools": ["repo_search", "fs_read"],
        "skills": ["code-reviewer", "security-checklist"],
        "tags": ["engineering", "review"],
    },
    {
        "slug": "cs-onboarding-agent",
        "name": "CS Onboarding Agent",
        "role": "worker",
        "department": "Customer Success",
        "description": "Guides customer onboarding milestones.",
        "capabilities": ["onboarding", "account_health"],
        "allowed_tools": ["knowledge_search"],
        "skills": ["onboarding-playbook", "support-reply-drafter"],
        "tags": ["customer_success"],
    },
    {
        "slug": "competitive-intel-agent",
        "name": "Competitive Intel Agent",
        "role": "worker",
        "department": "Sales",
        "description": "Builds competitor tear-downs for sales.",
        "capabilities": ["competitive_analysis", "web_research"],
        "allowed_tools": ["web_search", "web_fetch"],
        "skills": ["competitor-teardown", "web-research-specialist"],
        "tags": ["sales", "research"],
    },
    {
        "slug": "experiment-designer",
        "name": "Experiment Designer",
        "role": "worker",
        "department": "R&D",
        "description": "Designs hypotheses and measurement plans.",
        "capabilities": ["experiment_planning", "metrics_design"],
        "allowed_tools": ["knowledge_search", "web_search"],
        "skills": ["hypothesis-designer", "literature-reviewer"],
        "tags": ["research"],
    },
]
