BUILTIN_MODEL_CAPABILITIES: list[dict] = [
    {
        "provider_type": "openai",
        "model_slug": "gpt-4.1-mini",
        "display_name": "GPT-4.1 mini",
        "supports_tools": True,
        "supports_vision": False,
        "max_context_tokens": 128000,
        "cost_per_1k_input": 0.0004,
        "cost_per_1k_output": 0.0016,
    },
    {
        "provider_type": "openai",
        "model_slug": "gpt-4.1",
        "display_name": "GPT-4.1",
        "supports_tools": True,
        "supports_vision": True,
        "max_context_tokens": 128000,
        "cost_per_1k_input": 0.002,
        "cost_per_1k_output": 0.008,
    },
    {
        "provider_type": "openai",
        "model_slug": "gpt-4o-mini",
        "display_name": "GPT-4o mini",
        "supports_tools": True,
        "supports_vision": True,
        "max_context_tokens": 128000,
        "cost_per_1k_input": 0.00015,
        "cost_per_1k_output": 0.0006,
    },
    {
        "provider_type": "openai_compatible",
        "model_slug": "gpt-4.1-mini",
        "display_name": "OpenAI-compatible GPT-4.1 mini",
        "supports_tools": True,
        "supports_vision": False,
        "max_context_tokens": 128000,
        "cost_per_1k_input": 0.0004,
        "cost_per_1k_output": 0.0016,
    },
    {
        "provider_type": "openai_compatible",
        "model_slug": "gpt-4.1",
        "display_name": "OpenAI-compatible GPT-4.1",
        "supports_tools": True,
        "supports_vision": True,
        "max_context_tokens": 128000,
        "cost_per_1k_input": 0.002,
        "cost_per_1k_output": 0.008,
    },
    {
        "provider_type": "ollama",
        "model_slug": "llama3.2",
        "display_name": "Llama 3.2",
        "supports_tools": False,
        "supports_vision": False,
        "max_context_tokens": 8192,
        "cost_per_1k_input": 0.0,
        "cost_per_1k_output": 0.0,
    },
    {
        "provider_type": "ollama",
        "model_slug": "llama3.1:8b",
        "display_name": "Llama 3.1 8B",
        "supports_tools": False,
        "supports_vision": False,
        "max_context_tokens": 8192,
        "cost_per_1k_input": 0.0,
        "cost_per_1k_output": 0.0,
    },
    {
        "provider_type": "ollama",
        "model_slug": "qwen2.5-coder:7b",
        "display_name": "Qwen 2.5 Coder 7B",
        "supports_tools": False,
        "supports_vision": False,
        "max_context_tokens": 32768,
        "cost_per_1k_input": 0.0,
        "cost_per_1k_output": 0.0,
    },
]
