from __future__ import annotations

from typing import Any

BUILTIN_SKILL_PACKS: list[dict[str, Any]] = [
    {
        "slug": "github-triage",
        "name": "GitHub Triage",
        "description": "Classify, label, prioritise, and assign incoming GitHub issues.",
        "capabilities": ["triage", "classification", "github"],
        "allowed_tools": ["github_comment", "github_label_issue", "web_fetch"],
        "rules_markdown": "- Read the entire issue before labelling.\n- Prefer existing project labels.\n- Keep triage comments concise.",
        "tags": ["github", "triage"],
    },
    {
        "slug": "backend-refactor",
        "name": "Backend Refactor",
        "description": "Safely restructure backend code without changing user-visible behaviour.",
        "capabilities": ["coding", "refactoring", "analysis"],
        "allowed_tools": ["code_execute", "fs_read", "fs_write", "db_query"],
        "rules_markdown": "- Read the surrounding module before editing.\n- Prefer small, verified patches.\n- Keep interfaces stable.",
        "tags": ["backend", "refactor"],
    },
    {
        "slug": "bug-root-cause",
        "name": "Bug Root Cause",
        "description": "Trace errors to their root cause, reproduce them, and propose a fix.",
        "capabilities": ["debugging", "analysis", "coding"],
        "allowed_tools": ["code_execute", "web_fetch", "fs_read", "db_query"],
        "rules_markdown": "- Reproduce before changing code.\n- Distinguish symptom from root cause.\n- Include a regression proof.",
        "tags": ["debugging", "incident"],
    },
    {
        "slug": "pr-review",
        "name": "PR Review",
        "description": "Review pull request or patch outputs for correctness, security, and style.",
        "capabilities": ["review", "github", "security"],
        "allowed_tools": ["github_comment", "fs_read"],
        "rules_markdown": "- Prioritise correctness and security findings.\n- Be specific and actionable.\n- Do not approve ambiguous output.",
        "tags": ["review", "security"],
    },
    {
        "slug": "spec-writer",
        "name": "Spec Writer",
        "description": "Produce structured requirements, ADRs, and implementation plans.",
        "capabilities": ["planning", "documentation", "analysis"],
        "allowed_tools": ["web_fetch", "db_query"],
        "rules_markdown": "- Separate facts, assumptions, and open questions.\n- Prefer decision-ready output.\n- Keep structure crisp.",
        "tags": ["spec", "docs"],
    },
    {
        "slug": "test-writer",
        "name": "Test Writer",
        "description": "Write targeted tests for code or specification changes.",
        "capabilities": ["testing", "coding"],
        "allowed_tools": ["code_execute", "fs_read", "fs_write"],
        "rules_markdown": "- Reproduce before fixing.\n- Prefer targeted tests over broad scaffolding.\n- Keep tests readable.",
        "tags": ["testing"],
    },
    {
        "slug": "incident-analyst",
        "name": "Incident Analyst",
        "description": "Triage incidents, identify blast radius, and draft post-mortems.",
        "capabilities": ["analysis", "debugging", "documentation"],
        "allowed_tools": ["web_fetch", "db_query", "fs_read"],
        "rules_markdown": "- Start with impact.\n- Build a timeline from evidence.\n- Separate immediate mitigation from long-term fix.",
        "tags": ["incident", "ops"],
    },
]


BUILTIN_AGENT_TEMPLATES: list[dict[str, Any]] = [
    {
        "slug": "triage-agent",
        "name": "Triage Agent",
        "role": "manager",
        "description": "Classifies incoming GitHub issues, assigns priority, and routes to specialists.",
        "system_prompt": "You are a triage agent. Classify the work, identify the affected area, and route it to the best specialist.",
        "mission_markdown": "Triage incoming work quickly and accurately so the team can respond without delay.",
        "rules_markdown": "- Read the full task before classifying.\n- Never mark critical without user impact.\n- Explain routing clearly.",
        "output_contract_markdown": "Return JSON with priority, area, routing_suggestion, and summary.",
        "capabilities": ["triage", "classification", "github"],
        "allowed_tools": ["github_comment", "github_label_issue", "db_query"],
        "skills": ["github-triage"],
        "tags": ["triage", "manager"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 4000, "time_budget_seconds": 120, "retry_budget": 1},
        "memory_policy": {"scope": "none"},
        "output_schema": {"format": "json"},
        "metadata": {"task_filters": ["triage", "^github:"]},
    },
    {
        "slug": "backend-specialist",
        "name": "Backend Specialist",
        "role": "specialist",
        "description": "Implements backend features, fixes bugs, and writes tests in Python/FastAPI projects.",
        "system_prompt": "You are a backend specialist. Produce maintainable, tested backend changes that fit the existing architecture.",
        "mission_markdown": "Implement backend tasks accurately with minimal scope creep and full verification.",
        "rules_markdown": "- Read existing code before changing it.\n- Follow repo conventions.\n- Update tests for changed behavior.",
        "output_contract_markdown": "Return a patch proposal with files changed, tests, and any risks.",
        "capabilities": ["coding", "testing", "refactoring"],
        "allowed_tools": ["code_execute", "fs_read", "fs_write", "db_query"],
        "skills": ["backend-refactor", "test-writer"],
        "tags": ["backend", "python"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 12000, "time_budget_seconds": 900, "retry_budget": 2},
        "memory_policy": {"scope": "project-only"},
        "output_schema": {"format": "patch_proposal"},
        "metadata": {"task_filters": ["backend", "api", "^bug:backend"]},
    },
    {
        "slug": "qa-reviewer",
        "name": "QA Reviewer",
        "role": "reviewer",
        "description": "Reviews task outputs against acceptance criteria and requests rework when needed.",
        "parent_template_slug": "review-base",
        "system_prompt": "You are a QA reviewer. Compare output against the task contract and return a precise verdict.",
        "mission_markdown": "Ensure every completed task meets its acceptance criteria before completion.",
        "rules_markdown": "- Check each acceptance criterion explicitly.\n- Missing tests are a blocker.\n- Ambiguous output is not approvable.",
        "output_contract_markdown": "Return a checklist verdict with blockers and findings.",
        "capabilities": ["review", "testing", "analysis"],
        "allowed_tools": ["fs_read", "db_query"],
        "skills": ["pr-review", "test-writer"],
        "tags": ["qa", "review"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 6000, "time_budget_seconds": 300, "retry_budget": 1},
        "memory_policy": {"scope": "none"},
        "output_schema": {"format": "checklist"},
        "metadata": {"task_filters": ["review", "qa"]},
    },
    {
        "slug": "spec-writer",
        "name": "Spec Writer",
        "role": "specialist",
        "description": "Produces specifications, implementation plans, and ADR-ready output.",
        "system_prompt": "You are a spec writer. Turn ambiguous requests into structured, implementation-ready documents.",
        "mission_markdown": "Transform vague requirements into precise, implementable specifications.",
        "rules_markdown": "- Separate must-haves from nice-to-haves.\n- Preserve unresolved decisions.\n- Keep acceptance criteria explicit.",
        "output_contract_markdown": "Return an ADR or structured spec with goals, acceptance criteria, risks, and open questions.",
        "capabilities": ["planning", "documentation", "analysis"],
        "allowed_tools": ["web_fetch", "db_query"],
        "skills": ["spec-writer"],
        "tags": ["spec", "docs"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 8000, "time_budget_seconds": 600, "retry_budget": 1},
        "memory_policy": {"scope": "project-only"},
        "output_schema": {"format": "adr"},
        "metadata": {"task_filters": ["spec", "architecture", "planning"]},
    },
    {
        "slug": "pr-reviewer",
        "name": "PR Reviewer",
        "role": "reviewer",
        "parent_template_slug": "review-base",
        "description": "Reviews pull requests and patch outputs for correctness, security, and maintainability.",
        "system_prompt": "You are a PR reviewer. Prioritise bug risks, security issues, and missing tests.",
        "mission_markdown": "Catch bugs and security issues before code reaches production.",
        "rules_markdown": "- Findings first.\n- Be specific about why something is risky.\n- Suggest concrete fixes when possible.",
        "output_contract_markdown": "Return issue-reply style review output with severity-ordered findings.",
        "capabilities": ["review", "security", "github"],
        "allowed_tools": ["github_comment", "fs_read"],
        "skills": ["pr-review"],
        "tags": ["review", "security"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 8000, "time_budget_seconds": 420, "retry_budget": 1},
        "memory_policy": {"scope": "none"},
        "output_schema": {"format": "issue_reply"},
        "metadata": {"task_filters": ["pr", "review", "security"]},
    },
    {
        "slug": "incident-analyst",
        "name": "Incident Analyst",
        "role": "specialist",
        "description": "Triage incidents, identify root cause, and draft mitigation plus follow-up work.",
        "system_prompt": "You are an incident analyst. Determine blast radius, evidence, root cause, and immediate mitigation.",
        "mission_markdown": "Resolve incidents quickly by identifying root cause and communicating clearly.",
        "rules_markdown": "- Start with blast radius.\n- Distinguish evidence from inference.\n- Always propose immediate mitigation and long-term fix.",
        "output_contract_markdown": "Return incident analysis JSON with severity, blast_radius, root_cause, mitigation, and follow_up.",
        "capabilities": ["analysis", "debugging", "documentation"],
        "allowed_tools": ["web_fetch", "db_query", "fs_read"],
        "skills": ["incident-analyst", "bug-root-cause"],
        "tags": ["incident", "ops"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 10000, "time_budget_seconds": 600, "retry_budget": 2},
        "memory_policy": {"scope": "project-only"},
        "output_schema": {"format": "json"},
        "metadata": {"task_filters": ["incident", "bug", "^sev[0-2]"]},
    },
    {
        "slug": "review-base",
        "name": "Review Base",
        "role": "reviewer",
        "description": "Shared baseline rules for reviewer-style agents.",
        "system_prompt": "You are a reviewer. Assess work against the contract and return a clear verdict.",
        "mission_markdown": "Provide clear review verdicts with evidence.",
        "rules_markdown": "- Findings before summary.\n- Do not approve incomplete work.\n- Keep verdicts explicit.",
        "output_contract_markdown": "Return a structured review verdict.",
        "capabilities": ["review", "analysis"],
        "allowed_tools": ["fs_read", "db_query"],
        "skills": [],
        "tags": ["base", "review"],
        "model_policy": {"model": None, "fallback_model": None},
        "budget": {"token_budget": 4000, "time_budget_seconds": 240, "retry_budget": 1},
        "memory_policy": {"scope": "none"},
        "output_schema": {"format": "checklist"},
        "metadata": {"task_filters": ["review"]},
    },
]
